[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/splash/*"
  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
  Cache-Control = "public, max-age=86400, must-revalidate"