name: Build Test

on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches-ignore:
      - main
      - develop

jobs:
  build-test-apk:
    name: "build test apk 🔨"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PE_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PE_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PE_AWS_REGION }}

      - name: Download credential files
        run: |
          aws s3 cp s3://${{ secrets.PE_PRIVATE_AWS_S3_BUCKET_NAME }}/credentials/client/paladins-edge-stage.env ./paladins-edge.env
          aws s3 cp s3://${{ secrets.PE_PRIVATE_AWS_S3_BUCKET_NAME }}/credentials/client/google-services.json ./android/app/
          aws s3 cp s3://${{ secrets.PE_PRIVATE_AWS_S3_BUCKET_NAME }}/credentials/client/upload-keystore.jks ./android/app/
          aws s3 cp s3://${{ secrets.PE_PRIVATE_AWS_S3_BUCKET_NAME }}/credentials/client/key.properties ./android/

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ secrets.FLUTTER_VERSION }}

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build apk
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Get release notes
        run: git log -1 --pretty="TEST BUILD - Commit %h%n- Date %cs%n- %s" > release_notes.txt

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:280154424805:android:06755c7776c617c0aa1b0c
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Developers
          releaseNotesFile: ./release_notes.txt
          file: ./build/app/outputs/flutter-apk/app-release.apk
